name: across

services:
  app:
    build:
      context: ..
      dockerfile: containers/Dockerfile
      target: prod
    ports:
      - 8001:8001
    environment:
      APP_ENV: prod
    command: uvicorn across_data_ingestion.main:app --host 0.0.0.0 --port 8001